---
extends: default

ignore:
  - secrets/
  - tests/lib/

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
